name: Dynamic configuration demo
on:
  push:
jobs:
  demo:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate version
        run: |
          DYNAMIC_VERSION="v2.0.${{ github.run_number }}"
          echo "MY_VERSIONS=$DYNAMIC_VERSION" >> $GITHUB_ENV
      - name: Display version
        run: echo " Deployed version is $MY_VERSIONS"
      
        
