name: Dynamic configuration demo
on:
  push:
jobs:
  demo:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate version
        run: |
          VERSION_NUMBER = $(( 5 + ${{ github.run_number }}))
          DYNAMIC_VERSION="v2.0.$VERSION_NUMBER
          echo "MY_VERSIONS=$DYNAMIC_VERSION" >> $GITHUB_ENV
      - name: Display version
        run: echo " Deployed version is $MY_VERSIONS"
      
        
